### ISSUE TITLE
Recommendation: another trimming script

### ISSUE THREAD

**Issue by teoman002** [RubenNL/stackdump-lowram#1]
Six months ago, I wrote a bash/c++ script that reduces the stackoverflow database size.
https://gitlab.com/teoman002/shrink-the-stack-xml

There is an entry in `setup_script_stackoverflow.sh` that allows you to choose how much data is deleted:
`./PostFilter.o -score=3 -viewcount=3000 -favcount=2`

Each parameter flag works internally with an "Either Or Operation".
A **post is deleted** if it has score **lower than** 3. 
**or is preserved** if it either has a **viewcount higher than** 3000 or a **favcount higher than** 2

Due to the compiler optimization it only takes 8 minutes to reduce 50 GB to 4 GB.
That is dependant on the hardware ofc. (Overclocked I7 4.2 Ghz single threaded, 7200 RPM HDD)

It is a FOSS license, so you can take what you want and improve it.

**Comment by ryanschulz46** [comment]
Does this shrink down "PostHistory" and "Answers" though? Although Posts, Users, and Comments are trimmed, wont the RAM fill up when it try's to process all the questions and answers?

**Comment by RubenNL** [comment]
It looks like your script doesn't sort the Posts.xml file. This means that it will still eat your ram, which was my main reason why I made this script.

https://bitbucket.org/samuel.lai/stackdump/issues/16/memoryerror-cannot-import-stackoverflow

By sorting the posts.xml file, the amount of ram required stays constant.

**Comment by teoman002** [comment]
That's right, its not a fix for the RAM problem. May I ask, what needs to be sorted to reduce the amount of used RAM?
Is it the ID of a 'row'?
